// Shared category list used by Expenses and Budgets so both stay in sync.
export const CATEGORIES = [
  "general",
  "food",
  "groceries",
  "eating out",
  "travel",
  "transport",
  "fuel",
  "shopping",
  "clothing",
  "bills",
  "rent",
  "utilities",
  "internet",
  "phone",
  "entertainment",
  "subscriptions",
  "health",
  "fitness",
  "education",
  "kids",
  "pets",
  "gifts",
  "personal care",
  "insurance",
  "emi",
  "investments",
  "savings",
  "salary",
  "charity",
  "special",
  "other",
] as const;

export type Category = (typeof CATEGORIES)[number];
